language: node_js
node_js:
  - "8.1.4"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "npm install"
  - "npm install bower -g"
  - "bower install"
  - "gem install scss_lint"
script:
  - "gulp dev-ci"
  - "gulp test"
